### ISSUE TITLE
Server crash when client ctl-c's out

### ISSUE THREAD

**Issue by ghost** [zachtheclimber/GoCLC#1]
When the client exits with a `ctl-c` input, it causes the following server crash:
```
panic: runtime error: index out of range [0] with length 0

goroutine 8 [running]:
server.chat(0x5575e0, 0xc000010058, 0xc0000c2100)
        /home/zachtheclimber/coding/goclc/server/server.go:51 +0x26a
server.handleConn(0x5575e0, 0xc000010058)
        /home/zachtheclimber/coding/goclc/server/server.go:30 +0x147
created by server.Listen
        /home/zachtheclimber/coding/goclc/server/server.go:22 +0x1f0
exit status 2
```

Need to make that input cause the loop to break, rather than continuing and running `if command[0] == '/'`.

**Comment by ghost** [comment]
This issue is fixed with commit [2831b19](https://github.com/zachtheclimber/goclc/commit/2831b19ee688646323ba4856c54396904eaa0c91). The crash was caused by any sort of empty input, not just `ctl-c`.
